/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.scdproject;

import javax.swing.JPanel;

/**
 *
 * @author Valeena Afzal
 */
public class EntryOperator extends javax.swing.JFrame {

    /**
     * Creates new form EntryOperator
     */
    public EntryOperator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContentPane = new javax.swing.JPanel();
        Layers = new javax.swing.JLayeredPane();
        InventoryPanel = new javax.swing.JPanel();
        Manage = new javax.swing.JPanel();
        Formpanel = new javax.swing.JPanel();
        ManageInv = new javax.swing.JPanel();
        InvType = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Name = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        Category = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        Quantity = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        Price = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        MButtonsP = new javax.swing.JPanel();
        ButtonsInv = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        InvHeadingP = new javax.swing.JPanel();
        Heading1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Search = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        OrderPanel = new javax.swing.JPanel();
        Manage1 = new javax.swing.JPanel();
        Formpanel1 = new javax.swing.JPanel();
        ManageInv1 = new javax.swing.JPanel();
        InvType1 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        Name1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        Category1 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        Quantity1 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        Price1 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        CNIC = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        CalenderPanel = new javax.swing.JPanel();
        OrderDate = new javax.swing.JLabel();
        jDayChooser2 = new com.toedter.calendar.JDayChooser();
        InvHeadingP1 = new javax.swing.JPanel();
        Heading2 = new javax.swing.JLabel();
        MButtonsP2 = new javax.swing.JPanel();
        ButtonsInv2 = new javax.swing.JPanel();
        AddOrder = new javax.swing.JButton();
        EditOrder = new javax.swing.JButton();
        DeleteOrder = new javax.swing.JButton();
        PrintOrder = new javax.swing.JButton();
        ClearOrder = new javax.swing.JButton();
        ViewInv1 = new javax.swing.JPanel();
        HeadingPanel1 = new javax.swing.JPanel();
        Heading3 = new javax.swing.JLabel();
        TablePanel1 = new javax.swing.JPanel();
        PTable1 = new javax.swing.JScrollPane();
        Tables1 = new javax.swing.JTable();
        MailPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jFileChooser1 = new javax.swing.JFileChooser();
        jButton6 = new javax.swing.JButton();
        ViewInv2 = new javax.swing.JPanel();
        HeadingPanel2 = new javax.swing.JPanel();
        Heading4 = new javax.swing.JLabel();
        TablePanel2 = new javax.swing.JPanel();
        PTable2 = new javax.swing.JScrollPane();
        Tables2 = new javax.swing.JTable();
        Menu = new javax.swing.JPanel();
        Logo = new javax.swing.JPanel();
        TLogo = new javax.swing.JLabel();
        Buttons = new javax.swing.JPanel();
        Inventory = new javax.swing.JButton();
        Inventory1 = new javax.swing.JButton();
        Orders = new javax.swing.JButton();
        Mails = new javax.swing.JButton();
        Mails1 = new javax.swing.JButton();
        Buttons1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ContentPane.setLayout(new java.awt.GridLayout(1, 0));

        Layers.setLayout(new java.awt.CardLayout());

        InventoryPanel.setBackground(new java.awt.Color(255, 153, 255));
        InventoryPanel.setLayout(new java.awt.GridLayout(1, 0));

        Manage.setBackground(new java.awt.Color(255, 255, 255));
        Manage.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Formpanel.setBackground(new java.awt.Color(255, 255, 255));
        Formpanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        ManageInv.setBackground(new java.awt.Color(255, 255, 255));
        ManageInv.setLayout(new java.awt.GridLayout(5, 1, 0, 30));

        InvType.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        InvType.setForeground(new java.awt.Color(153, 0, 0));
        InvType.setText("Select Type");
        ManageInv.add(InvType);

        jComboBox1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(153, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fruit Trees", "Trees", "Shrubs", "Herbs", "Climbers", "Creepers", "None" }));
        ManageInv.add(jComboBox1);

        Name.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(153, 0, 0));
        Name.setText("Name");
        ManageInv.add(Name);

        jTextField3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(153, 0, 0));
        ManageInv.add(jTextField3);

        Category.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Category.setForeground(new java.awt.Color(153, 0, 0));
        Category.setText("Category");
        ManageInv.add(Category);

        jComboBox2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(153, 0, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plants", "Seeds", "Tools" }));
        ManageInv.add(jComboBox2);

        Quantity.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Quantity.setForeground(new java.awt.Color(153, 0, 0));
        Quantity.setText("Quantity");
        ManageInv.add(Quantity);

        jTextField2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(153, 0, 0));
        ManageInv.add(jTextField2);

        Price.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Price.setForeground(new java.awt.Color(153, 0, 0));
        Price.setText("Price");
        ManageInv.add(Price);

        jTextField4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(153, 0, 0));
        ManageInv.add(jTextField4);

        Formpanel.add(ManageInv);

        MButtonsP.setBackground(new java.awt.Color(255, 255, 255));
        MButtonsP.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        ButtonsInv.setBackground(new java.awt.Color(255, 255, 255));
        ButtonsInv.setLayout(new java.awt.GridLayout(1, 0, 30, 0));

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        ButtonsInv.add(jButton1);

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        ButtonsInv.add(jButton2);

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        ButtonsInv.add(jButton3);

        jButton4.setBackground(new java.awt.Color(153, 0, 0));
        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Clear");
        ButtonsInv.add(jButton4);

        MButtonsP.add(ButtonsInv);

        InvHeadingP.setBackground(new java.awt.Color(255, 255, 255));

        Heading1.setBackground(new java.awt.Color(153, 0, 0));
        Heading1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Heading1.setForeground(new java.awt.Color(153, 0, 0));
        Heading1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading1.setText("Manage Inventory");
        InvHeadingP.add(Heading1);

        javax.swing.GroupLayout ManageLayout = new javax.swing.GroupLayout(Manage);
        Manage.setLayout(ManageLayout);
        ManageLayout.setHorizontalGroup(
            ManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Formpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MButtonsP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(InvHeadingP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ManageLayout.setVerticalGroup(
            ManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InvHeadingP, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Formpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(MButtonsP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(374, Short.MAX_VALUE))
        );

        InventoryPanel.add(Manage);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));

        jList1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(153, 0, 0));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        Search.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        Search.setForeground(new java.awt.Color(153, 0, 0));
        Search.setText("Search");

        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 0, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Search)
                        .addGap(85, 85, 85)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(441, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 66, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        InventoryPanel.add(jPanel3);

        Layers.add(InventoryPanel, "card2");

        OrderPanel.setBackground(new java.awt.Color(255, 255, 255));
        OrderPanel.setLayout(new java.awt.GridLayout(1, 0));

        Manage1.setBackground(new java.awt.Color(255, 255, 255));
        Manage1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Formpanel1.setBackground(new java.awt.Color(255, 255, 255));
        Formpanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        ManageInv1.setBackground(new java.awt.Color(255, 255, 255));
        ManageInv1.setLayout(new java.awt.GridLayout(3, 4, 15, 30));

        InvType1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        InvType1.setForeground(new java.awt.Color(153, 0, 0));
        InvType1.setText("Select Type");
        ManageInv1.add(InvType1);

        jComboBox3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(153, 0, 0));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fruit Trees", "Trees", "Shrubs", "Herbs", "Climbers", "Creepers", "None" }));
        ManageInv1.add(jComboBox3);

        Name1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Name1.setForeground(new java.awt.Color(153, 0, 0));
        Name1.setText("Name");
        ManageInv1.add(Name1);

        jTextField5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(153, 0, 0));
        ManageInv1.add(jTextField5);

        Category1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Category1.setForeground(new java.awt.Color(153, 0, 0));
        Category1.setText("Category");
        ManageInv1.add(Category1);

        jComboBox4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(153, 0, 0));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plants", "Seeds", "Tools" }));
        ManageInv1.add(jComboBox4);

        Quantity1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Quantity1.setForeground(new java.awt.Color(153, 0, 0));
        Quantity1.setText("Quantity");
        ManageInv1.add(Quantity1);

        jTextField6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(153, 0, 0));
        ManageInv1.add(jTextField6);

        Price1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Price1.setForeground(new java.awt.Color(153, 0, 0));
        Price1.setText("Price");
        ManageInv1.add(Price1);

        jTextField7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(153, 0, 0));
        ManageInv1.add(jTextField7);

        CNIC.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        CNIC.setForeground(new java.awt.Color(153, 0, 0));
        CNIC.setText("CNIC");
        ManageInv1.add(CNIC);

        jTextField8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(153, 0, 0));
        ManageInv1.add(jTextField8);

        Formpanel1.add(ManageInv1);

        CalenderPanel.setBackground(new java.awt.Color(255, 255, 255));
        CalenderPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        OrderDate.setBackground(new java.awt.Color(255, 255, 255));
        OrderDate.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        OrderDate.setForeground(new java.awt.Color(153, 0, 0));
        OrderDate.setText("Date");
        OrderDate.setPreferredSize(new java.awt.Dimension(130, 50));
        CalenderPanel.add(OrderDate);

        jDayChooser2.setBackground(new java.awt.Color(255, 255, 255));
        CalenderPanel.add(jDayChooser2);

        InvHeadingP1.setBackground(new java.awt.Color(255, 255, 255));

        Heading2.setBackground(new java.awt.Color(153, 0, 0));
        Heading2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Heading2.setForeground(new java.awt.Color(153, 0, 0));
        Heading2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading2.setText("Manage Orders");
        InvHeadingP1.add(Heading2);

        MButtonsP2.setBackground(new java.awt.Color(255, 255, 255));
        MButtonsP2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        ButtonsInv2.setBackground(new java.awt.Color(255, 255, 255));
        ButtonsInv2.setLayout(new java.awt.GridLayout(1, 0, 30, 0));

        AddOrder.setBackground(new java.awt.Color(153, 0, 0));
        AddOrder.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        AddOrder.setForeground(new java.awt.Color(255, 255, 255));
        AddOrder.setText("Add");
        ButtonsInv2.add(AddOrder);

        EditOrder.setBackground(new java.awt.Color(153, 0, 0));
        EditOrder.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        EditOrder.setForeground(new java.awt.Color(255, 255, 255));
        EditOrder.setText("Edit");
        EditOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditOrderActionPerformed(evt);
            }
        });
        ButtonsInv2.add(EditOrder);

        DeleteOrder.setBackground(new java.awt.Color(153, 0, 0));
        DeleteOrder.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DeleteOrder.setForeground(new java.awt.Color(255, 255, 255));
        DeleteOrder.setText("Delete");
        DeleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteOrderActionPerformed(evt);
            }
        });
        ButtonsInv2.add(DeleteOrder);

        PrintOrder.setBackground(new java.awt.Color(153, 0, 0));
        PrintOrder.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        PrintOrder.setForeground(new java.awt.Color(255, 255, 255));
        PrintOrder.setText("Print");
        PrintOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintOrderActionPerformed(evt);
            }
        });
        ButtonsInv2.add(PrintOrder);

        ClearOrder.setBackground(new java.awt.Color(153, 0, 0));
        ClearOrder.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ClearOrder.setForeground(new java.awt.Color(255, 255, 255));
        ClearOrder.setText("Clear");
        ButtonsInv2.add(ClearOrder);

        MButtonsP2.add(ButtonsInv2);

        javax.swing.GroupLayout Manage1Layout = new javax.swing.GroupLayout(Manage1);
        Manage1.setLayout(Manage1Layout);
        Manage1Layout.setHorizontalGroup(
            Manage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Formpanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CalenderPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(InvHeadingP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MButtonsP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Manage1Layout.setVerticalGroup(
            Manage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Manage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InvHeadingP1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Formpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(CalenderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(MButtonsP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(375, Short.MAX_VALUE))
        );

        OrderPanel.add(Manage1);

        ViewInv1.setBackground(new java.awt.Color(255, 255, 255));
        ViewInv1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        HeadingPanel1.setBackground(new java.awt.Color(255, 255, 255));
        HeadingPanel1.setLayout(new java.awt.GridLayout(1, 0));

        Heading3.setBackground(new java.awt.Color(153, 0, 0));
        Heading3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Heading3.setForeground(new java.awt.Color(153, 0, 0));
        Heading3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading3.setText("Inventory List");
        HeadingPanel1.add(Heading3);

        TablePanel1.setBackground(new java.awt.Color(255, 255, 255));
        TablePanel1.setForeground(new java.awt.Color(153, 0, 0));
        TablePanel1.setLayout(new java.awt.GridLayout(1, 0));

        PTable1.setBackground(new java.awt.Color(153, 0, 0));
        PTable1.setBorder(null);
        PTable1.setForeground(new java.awt.Color(255, 255, 255));
        PTable1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        Tables1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Tables1.setForeground(new java.awt.Color(153, 0, 0));
        Tables1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Type", "Name", "Date", "CNIC", "Quantity", "Price", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tables1.setGridColor(new java.awt.Color(153, 0, 0));
        Tables1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        Tables1.setSelectionForeground(new java.awt.Color(255, 153, 204));
        PTable1.setViewportView(Tables1);

        TablePanel1.add(PTable1);

        javax.swing.GroupLayout ViewInv1Layout = new javax.swing.GroupLayout(ViewInv1);
        ViewInv1.setLayout(ViewInv1Layout);
        ViewInv1Layout.setHorizontalGroup(
            ViewInv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeadingPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TablePanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );
        ViewInv1Layout.setVerticalGroup(
            ViewInv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewInv1Layout.createSequentialGroup()
                .addComponent(HeadingPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TablePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE))
        );

        OrderPanel.add(ViewInv1);

        Layers.add(OrderPanel, "card3");

        MailPanel.setBackground(new java.awt.Color(255, 255, 255));
        MailPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MailPanel.setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAlignmentX(5.0F);

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setAlignmentX(5.0F);
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 550));

        jLabel2.setBackground(new java.awt.Color(153, 0, 0));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Subject");

        jTextField9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(153, 0, 0));

        jLabel4.setBackground(new java.awt.Color(153, 0, 0));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("From");

        jTextField11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(153, 0, 0));
        jTextField11.setText("valeenaafzal@gmail.com");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(153, 0, 0));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Content");

        jTextField12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(153, 0, 0));

        jLabel6.setBackground(new java.awt.Color(153, 0, 0));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Select Attachment");

        jLabel3.setBackground(new java.awt.Color(153, 0, 0));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Send To");

        jTextField10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(153, 0, 0));

        jLabel7.setBackground(new java.awt.Color(153, 0, 0));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("Send To");

        jButton6.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 0, 0));
        jButton6.setText("Send");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(357, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MailPanel.add(jPanel1);

        Layers.add(MailPanel, "card4");

        ViewInv2.setBackground(new java.awt.Color(255, 255, 255));
        ViewInv2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        HeadingPanel2.setBackground(new java.awt.Color(255, 255, 255));
        HeadingPanel2.setLayout(new java.awt.GridLayout(1, 0));

        Heading4.setBackground(new java.awt.Color(153, 0, 0));
        Heading4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Heading4.setForeground(new java.awt.Color(153, 0, 0));
        Heading4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading4.setText("Inventory List");
        HeadingPanel2.add(Heading4);

        TablePanel2.setBackground(new java.awt.Color(255, 255, 255));
        TablePanel2.setForeground(new java.awt.Color(153, 0, 0));
        TablePanel2.setLayout(new java.awt.GridLayout(1, 0));

        PTable2.setBackground(new java.awt.Color(153, 0, 0));
        PTable2.setBorder(null);
        PTable2.setForeground(new java.awt.Color(255, 255, 255));
        PTable2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        Tables2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Tables2.setForeground(new java.awt.Color(153, 0, 0));
        Tables2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Type", "Name", "Category", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tables2.setGridColor(new java.awt.Color(153, 0, 0));
        Tables2.setSelectionBackground(new java.awt.Color(255, 255, 255));
        Tables2.setSelectionForeground(new java.awt.Color(255, 153, 204));
        PTable2.setViewportView(Tables2);

        TablePanel2.add(PTable2);

        javax.swing.GroupLayout ViewInv2Layout = new javax.swing.GroupLayout(ViewInv2);
        ViewInv2.setLayout(ViewInv2Layout);
        ViewInv2Layout.setHorizontalGroup(
            ViewInv2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeadingPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TablePanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1323, Short.MAX_VALUE)
        );
        ViewInv2Layout.setVerticalGroup(
            ViewInv2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewInv2Layout.createSequentialGroup()
                .addComponent(HeadingPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TablePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE))
        );

        Layers.add(ViewInv2, "card5");

        ContentPane.add(Layers);

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Logo.setBackground(new java.awt.Color(255, 255, 255));

        TLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Valeena Afzal\\Documents\\NetBeansProjects\\SCDProject\\src\\main\\java\\com\\mycompany\\Images\\BudB.png")); // NOI18N

        Buttons.setBackground(new java.awt.Color(255, 255, 255));
        Buttons.setLayout(new java.awt.GridLayout(5, 0, 0, 30));

        Inventory.setBackground(new java.awt.Color(153, 0, 0));
        Inventory.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Inventory.setForeground(new java.awt.Color(255, 255, 255));
        Inventory.setIcon(new javax.swing.ImageIcon("C:\\Users\\Valeena Afzal\\Documents\\NetBeansProjects\\SCDProject\\src\\main\\java\\com\\mycompany\\Images\\icons8-warehouse-30.png")); // NOI18N
        Inventory.setText("Update Inventory");
        Inventory.setBorder(null);
        Inventory.setIconTextGap(15);
        Inventory.setMargin(new java.awt.Insets(1, 14, 2, 14));
        Inventory.setPreferredSize(new java.awt.Dimension(120, 50));
        Inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventoryActionPerformed(evt);
            }
        });
        Buttons.add(Inventory);

        Inventory1.setBackground(new java.awt.Color(153, 0, 0));
        Inventory1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Inventory1.setForeground(new java.awt.Color(255, 255, 255));
        Inventory1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Valeena Afzal\\Documents\\NetBeansProjects\\SCDProject\\src\\main\\java\\com\\mycompany\\Images\\icons8-list-view-30.png")); // NOI18N
        Inventory1.setText("Inventory List");
        Inventory1.setBorder(null);
        Inventory1.setIconTextGap(45);
        Inventory1.setMargin(new java.awt.Insets(1, 14, 2, 14));
        Inventory1.setPreferredSize(new java.awt.Dimension(120, 50));
        Inventory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inventory1ActionPerformed(evt);
            }
        });
        Buttons.add(Inventory1);

        Orders.setBackground(new java.awt.Color(153, 0, 0));
        Orders.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Orders.setForeground(new java.awt.Color(255, 255, 255));
        Orders.setIcon(new javax.swing.ImageIcon("C:\\Users\\Valeena Afzal\\Documents\\NetBeansProjects\\SCDProject\\src\\main\\java\\com\\mycompany\\Images\\icons8-order-30.png")); // NOI18N
        Orders.setText("Add Order");
        Orders.setIconTextGap(50);
        Orders.setPreferredSize(new java.awt.Dimension(120, 50));
        Orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdersActionPerformed(evt);
            }
        });
        Buttons.add(Orders);

        Mails.setBackground(new java.awt.Color(153, 0, 0));
        Mails.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Mails.setForeground(new java.awt.Color(255, 255, 255));
        Mails.setIcon(new javax.swing.ImageIcon("C:\\Users\\Valeena Afzal\\Documents\\NetBeansProjects\\SCDProject\\src\\main\\java\\com\\mycompany\\Images\\icons8-send-email-30.png")); // NOI18N
        Mails.setText("Email");
        Mails.setIconTextGap(80);
        Mails.setPreferredSize(new java.awt.Dimension(120, 50));
        Mails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MailsActionPerformed(evt);
            }
        });
        Buttons.add(Mails);

        Mails1.setBackground(new java.awt.Color(153, 0, 0));
        Mails1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Mails1.setForeground(new java.awt.Color(255, 255, 255));
        Mails1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Valeena Afzal\\Documents\\NetBeansProjects\\SCDProject\\src\\main\\java\\com\\mycompany\\Images\\icons8-logout-rounded-left-50.png")); // NOI18N
        Mails1.setBorder(null);
        Mails1.setIconTextGap(80);
        Mails1.setPreferredSize(new java.awt.Dimension(120, 50));
        Mails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mails1ActionPerformed(evt);
            }
        });
        Buttons.add(Mails1);

        Buttons1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Buttons1Layout = new javax.swing.GroupLayout(Buttons1);
        Buttons1.setLayout(Buttons1Layout);
        Buttons1Layout.setHorizontalGroup(
            Buttons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );
        Buttons1Layout.setVerticalGroup(
            Buttons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Buttons, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TLogo)
                    .addComponent(Buttons1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addComponent(TLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Buttons, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Buttons1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ContentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryActionPerformed
        SwitchPanels(InventoryPanel);
        // TODO add your handling code here:
    }//GEN-LAST:event_InventoryActionPerformed

    private void OrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdersActionPerformed
        SwitchPanels(OrderPanel);
        // TODO add your handling code here:
    }//GEN-LAST:event_OrdersActionPerformed

    private void MailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MailsActionPerformed
        SwitchPanels(MailPanel);
        // TODO add your handling code here:
    }//GEN-LAST:event_MailsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void EditOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditOrderActionPerformed

    private void DeleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteOrderActionPerformed

    private void PrintOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrintOrderActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void Mails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mails1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mails1ActionPerformed

    private void Inventory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inventory1ActionPerformed
         SwitchPanels(ViewInv2);

        // TODO add your handling code here:
    }//GEN-LAST:event_Inventory1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    public void SwitchPanels(JPanel panel)
    {
        Layers.removeAll();
        Layers.add(panel);
        Layers.repaint();
        Layers.revalidate();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntryOperator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntryOperator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntryOperator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntryOperator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntryOperator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddOrder;
    private javax.swing.JPanel Buttons;
    private javax.swing.JPanel Buttons1;
    private javax.swing.JPanel ButtonsInv;
    private javax.swing.JPanel ButtonsInv2;
    private javax.swing.JLabel CNIC;
    private javax.swing.JPanel CalenderPanel;
    private javax.swing.JLabel Category;
    private javax.swing.JLabel Category1;
    private javax.swing.JButton ClearOrder;
    private javax.swing.JPanel ContentPane;
    private javax.swing.JButton DeleteOrder;
    private javax.swing.JButton EditOrder;
    private javax.swing.JPanel Formpanel;
    private javax.swing.JPanel Formpanel1;
    private javax.swing.JLabel Heading1;
    private javax.swing.JLabel Heading2;
    private javax.swing.JLabel Heading3;
    private javax.swing.JLabel Heading4;
    private javax.swing.JPanel HeadingPanel1;
    private javax.swing.JPanel HeadingPanel2;
    private javax.swing.JPanel InvHeadingP;
    private javax.swing.JPanel InvHeadingP1;
    private javax.swing.JLabel InvType;
    private javax.swing.JLabel InvType1;
    private javax.swing.JButton Inventory;
    private javax.swing.JButton Inventory1;
    private javax.swing.JPanel InventoryPanel;
    private javax.swing.JLayeredPane Layers;
    private javax.swing.JPanel Logo;
    private javax.swing.JPanel MButtonsP;
    private javax.swing.JPanel MButtonsP2;
    private javax.swing.JPanel MailPanel;
    private javax.swing.JButton Mails;
    private javax.swing.JButton Mails1;
    private javax.swing.JPanel Manage;
    private javax.swing.JPanel Manage1;
    private javax.swing.JPanel ManageInv;
    private javax.swing.JPanel ManageInv1;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel OrderDate;
    private javax.swing.JPanel OrderPanel;
    private javax.swing.JButton Orders;
    private javax.swing.JScrollPane PTable1;
    private javax.swing.JScrollPane PTable2;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel Price1;
    private javax.swing.JButton PrintOrder;
    private javax.swing.JLabel Quantity;
    private javax.swing.JLabel Quantity1;
    private javax.swing.JButton Search;
    private javax.swing.JLabel TLogo;
    private javax.swing.JPanel TablePanel1;
    private javax.swing.JPanel TablePanel2;
    private javax.swing.JTable Tables1;
    private javax.swing.JTable Tables2;
    private javax.swing.JPanel ViewInv1;
    private javax.swing.JPanel ViewInv2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private com.toedter.calendar.JDayChooser jDayChooser2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
